#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Simple script to pick color quickly.

color=$(xcolor --format hex --preview-size 255 --scale 10)
image=/tmp/${color}.png

main() {
    if [[ "$color" ]]; then
        # copy color code to clipboard
        echo $color | tr -d "\n" | xclip -selection clipboard
        # generate preview
        convert -size 48x48 xc:"$color" ${image}
        # Remove the line below if you don't want the notification
    fi
}

# run the script
main

