#!/usr/bin/env bash

sudo -S modprobe -r psmouse <<<'password'
sudo systemctl restart systemd-timesyncd
sudo systemctl stop mariadb.service

xrandr --output eDP --mode 1366x768 --pos 0x0 --output HDMI-A-0 --mode 1280x1024 --pos 0x768 --above eDP

export _JAVA_AWT_WM_NONREPARENTING=1
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk

default_workspaces() {
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8'
	done
}

two_monitors_workspaces() {
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '5' '6' '7' '8' 
		bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4'
		bspc wm -O  "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"  
	else
		bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8'
	fi
}

two_monitors_workspaces

bspc config border_width 2
bspc config window_gap 5
bspc config split_ratio 0.50
bspc config focus_follows_pointer true 

bspc config focused_border_color "#373b41"
bspc config normal_border_color "#282a2e"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false 

bspc rule -a xterm-256color desktop='^1' follow=on focus=on
bspc rule -a St state=floating follow=on focus=on
bspc rule -a feh desktop='^5' follow=on focus=on state=floating
bspc rule -a pcmanfm desktop='^3' follow=on focus=on

killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

xsettingsd --config=~/.config/bspwm/xsettingsd &

sxhkd &

ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

feh --bg-scale /home/luis/Imágenes/catppuccin/cat-2.png /home/luis/Imágenes/catppuccin/aesthetic-3.jpg

~/.config/polybar/launch.sh &
picom &

exec mpd &
